uploads = []
outputs = []

[[generated]]
id = "Wdd4RetI-Jl1mLRkF9tN4"
uri = "file://artifacts/crypto-exchange/assets/images/icon.png"
type = "image"
title = "crypto exchange app icon"

[[generated]]
id = "8HH55jw_RSLnpL7LgMO3_"
uri = "file://artifacts/user-portal/public/invite-banner.png"
type = "image"
title = "invite hero banner"
