name: crypto_exchange_flutter
description: "ZEBVIX Crypto Exchange — Flutter mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  web_socket_channel: ^3.0.1
  google_fonts: ^6.2.1
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
