import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminRouter from "./admin";
import publicRouter from "./public";
import publicUserRouter from "./public-user";
import otpRouter from "./otp";
import marketsRouter from "./markets";
import paymentsRouter from "./payments";
import ordersRouter from "./orders";
import positionsRouter from "./positions";
import transferRouter from "./transfer";
import earnUserRouter from "./earn-user";
import feesRouter from "./fees";
import securityRouter from "./security";
import klinesRouter from "./klines";
import promoRouter from "./promo";
import redisAdminRouter from "./redis-admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(publicRouter);
router.use(publicUserRouter);
router.use(otpRouter);
router.use(marketsRouter);
router.use(paymentsRouter);
router.use(ordersRouter);
router.use(positionsRouter);
router.use(transferRouter);
router.use(earnUserRouter);
router.use(feesRouter);
router.use(securityRouter);
router.use(klinesRouter);
router.use(promoRouter);
router.use("/admin", redisAdminRouter);

export default router;
